### ISSUE TITLE
'Failed to load resource' when clicking on 'Stop recording' button

### ISSUE THREAD

**Issue by avivr** [samccone/ivy#4]
I get this error message when clicking 'stop recording' button:

GET blob:http://localhost:8001/be0ed196-5501-4b84-bcb3-48004d91a3f0 416 (Requested Range Not Satisfiable)

<img width="1007" alt="screen shot 2016-10-29 at 18 01 35" src="https://cloud.githubusercontent.com/assets/7034094/19831086/f343f320-9e01-11e6-8aed-19f36074d403.png">

Running:
Google Chrome   53.0.2785.143 (Official Build) (64-bit)
OS  Mac OS X 

Served from file-system via local web server - https://www.npmjs.com/package/serve

Videos are not shown in the lower pane.

Any ideas what can cause this? Thanks!

**Comment by samccone** [comment]
oh interesting.. I have never seen this before.

**Comment by avivr** [comment]
What server do you use to run it? on which browser?

**Comment by samccone** [comment]
This is a blob url and should not actually be hitting the server at all as it is just created locally in your browser.

https://github.com/samccone/ivy/blob/master/js/app.js#L56

**Comment by avivr** [comment]
ok, got it working with setting 'Experimental Web Platform features' in chrome://flags.
Found it after trying to run on FF (v44) and received this alert for some reason:  

> MediaRecorder is not supported by this browser.
> 
> Try Firefox 29 or later, or Chrome 47 or later, with Enable experimental Web Platform features enabled from chrome://flags.

Then went back to chrome and turned the flag on and it worked

**Comment by samccone** [comment]
:+1: :)
